services:
  gold-syncer:
    build: 
      context: .
      dockerfile: Dockerfile.syncer
    container_name: gold-syncer
    restart: always
    volumes:
      - ./app.db:/app/app.db:rw
      # Gerekirse JSON key mount etmek için
      #- ./service-account.json:/app/service-account.json:ro
